# -*- coding: utf-8 -*-
"""sharktank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGdIPU1bjYGiWkXKzOzRI1G6j24KMvEJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df=pd.read_csv('ShartankIndiaAllPitches.csv')
df

df.columns

df.index

df.shape

df.size

df.dtypes

df.head(5)

df.tail(5)

df.empty

df.any()

df.all()

df.dropna()

df.duplicated()

df.describe()

df.columns = df.columns.str.strip()

investor_columns = ['Anupam', 'Ashneer', 'Namita', 'Aman', 'Peyush', 'Vineeta', 'Ghazal']
for col in investor_columns:
    df[col] = df[col].apply(lambda x: 1 if x == 'Y' else 0)

df['Total Investors'] = df[investor_columns].sum(axis=1)

features = ['Equity', 'Debt (In lakhs INR)', 'Season', 'Total Investors']
target = 'Investment Amount (In Lakhs INR)'

df['Equity'] = df['Equity'].str.rstrip('%').astype(float)

X = df[features]
Y = df[target]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, Y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

plt.scatter(df['Equity'], df[target], alpha=0.5, color='blue')
plt.title('Equity vs Investment Amount')
plt.xlabel('Equity (%)')
plt.ylabel('Investment Amount (In Lakhs INR)')
plt.show()

df.plot(kind='bar',x='Episode Number', y='Investment Amount (In Lakhs INR)' )
plt.title('Investment Amount by Episode Number'),
plt.xlabel('Episode Number'),
plt.ylabel('Investment Amount (In Lakhs INR)')
plt.show()

df.plot(kind='hist', y='Investment Amount (In Lakhs INR)', width=0.50, color='r', x='Aman')